### ISSUE TITLE
Change to emby provided ffmpeg

### ISSUE THREAD

**Issue by darthShadow** [binhex/arch-emby#11]
From: https://emby.media/community/index.php?/topic/110285-how-to-update-ffmpeg-on-arch-linux/#comment-1161621

> On Arch Linux, Emby is using the system-installed ffmpeg by default.

> Now we have started publishing an Arch Linux package which allows easy installation of the same ffmpeg that is included in most of our other server installation packages and which is optimized for tone mapping, hardware acceleration and a number of other things in combination with Emby Server.
> 
> Installation
> 
> `pacman -U https://mediabrowser.github.io/embytools/emby-ffmpeg-bin-2022_05_07-1-x86_64.pkg.tar.zst`

> Please reboot the machine after installation.

**Comment by binhex** [comment]
thanks for this, i see the above is included in the official arch linux emby-server package so i am removing statically built ffmpeg from the build of the image.
