### ISSUE TITLE
Update to 3.3.x

### ISSUE THREAD

**Issue by ghost** [binhex/arch-emby#5]
hi binhex,

the new updates since 3.2.6 has some cool fixes and imporvenents.
can you pls update the image ?
https://github.com/MediaBrowser/Emby/releases

Thanks a lot!

**Comment by binhex** [comment]
waiting on emby dev to push the latest build to arch linux repo:-

https://emby.media/community/index.php?/topic/13120-arch-linux/page-10

**Comment by binhex** [comment]
This is now done.
