### ISSUE TITLE
Docker needs reversion to ffmpeg 4.0.2. 

### ISSUE THREAD

**Issue by Aterfax** [binhex/arch-emby#6]
See detail:

_Originally posted by @LukePulverenti in https://github.com/MediaBrowser/Emby/issues/3517#issuecomment-457456625_

**Comment by binhex** [comment]
soft linked emby static version of ffmpeg, so this SHOULD fix things up, please confirm as i dont use emby so i cant tell if its fixed or not.

**Comment by Aterfax** [comment]
Testing now:

Can confirm that this seems to have fixed the issue. Thanks!
