### ISSUE TITLE
[Request] Consider also releasing a version of Jellyfin?

### ISSUE THREAD

**Issue by Aterfax** [binhex/arch-emby#7]
Since there's been a fork made would you consider making a docker that includes hardware acceleration? (NVENC etc...)

https://github.com/jellyfin/jellyfin

**Comment by binhex** [comment]
im considering it :-)

**Comment by Aterfax** [comment]
Cheers hoss, I'm not sure that they've added NVENC support yet in their FFMPEG but I've jury rigged it on mine atm via docker device handling rather than nvidia-docker.

the tl;dr of it is, you need the drivers and kernel modules installed on unraid first, then inside the host.

You can see how I hacked it together here:  https://github.com/Aterfax/nvidiadriversonunraidinstaller

It looks like there's a proper plugin being put together too here: https://github.com/CHBMB/Unraid-NVIDIA-Plugin

But afaik, because the drivers (GPU and CUDA) need to match on host and docker image it needs there needs to be sync between both.

@CHBMB might need to expose some variable indicating what version drivers are being added to the kernel?

**Comment by binhex** [comment]
jellyfin is now done, should be visible in CA (unraid plugin) shortly, as far as gpu encoding goes im afraid i dont have a discrete gpu so you are going to have to figure that out on your own, good luck!.

**Comment by CHBMB** [comment]
The Nvidia plugin is still in development.  Give us time, idea is you don't need drivers in the container, as that ends up a real fustercluck
